### ISSUE TITLE
panc maven plugin needed for build-profile

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#180]
so either we try to figure out to get it rebuild or we remove it from https://github.com/quattor/maven-tools/blob/master/build-profile/pom.xml#L273

right now, there are no build tools that can handle new compiler version

**Comment by stdweird** [comment]
@kwaegema this is your issue

**Comment by jrha** [comment]
Hmm, is it actually used to accomplish anything useful, or is it just referenced?

**Comment by stdweird** [comment]
the naming suggests it does a pan syntax check of something
but we have (or should have) unittests that do that.

**Comment by ned21** [comment]
Looks like the [plugin source](https://github.com/quattor/pan/tree/master/panc-maven-plugin) has a pom.xml but I guess it's not built when you build the rest of the release. I agree it would appear to do the same job as a unit test which depends on having a profile compiled which includes pan/*.pan. Last time I checked not every component had a unit test which resulted in the PAN files being exercised. If we have good coverage now then it would be OK to drop it, otherwise it's a good way of ensuring 100% coverage of PAN files in the repo.

I don't have a working Java build system, does the pom.xml product anything we can push to the place we store the quattor-maven-plugin?

**Comment by stdweird** [comment]
@ned21 we were not able to get the pan maven plugins to build, for whatever obscure reason. so we dropped it, in order to be able to release pan again. i can have a look again at what is required for pan syntax unittest. however, we have (or should have) coverage checks in the template-library-core.
